### ISSUE TITLE
error in posting checkins

### ISSUE THREAD

**Issue by b3ll318** [pengwynn/gowalla#21]
i'm getting this error when creating checkins

NoMethodError: undefined method `bytesize' for {}:Hash

**Comment by ehutzelman** [comment]
Yeah unfortunately I don't think we've revisited the checkin code since Gowalla went to using oauth2 for authentication.  So the ability to perform checkins is broken right now.  

I'm doing some reading up on oauth2 and the Gowalla api to see how we can implement this using the oauth_token.  Unfortunately, it looks like Gowalla only supports authorization_code grant types, which means you will have to supply a callback URL to get the oauth_token, etc.  I'm wondering if there is still a way to get an oauth_token using a username/password to bypass the need for a callback.  Maybe Wynn will chime in on this.

**Comment by ehutzelman** [comment]
Ok, checkins should be working now as long as you are using an oauth token.  Version 0.5.8 just released.
