### ISSUE TITLE
error with gowalla.user

### ISSUE THREAD

**Issue by diemer** [pengwynn/gowalla#5]
When I call gowalla.user after instantiating a client I get a big nasty error from Faraday: RuntimeError: Did not recognize your engine specification. Please specify either a symbol or a class.
        from /home/BUS/djd226/.gems/gems/multi_json-0.0.4/lib/multi_json.rb:52:in `engine='
        from /home/BUS/djd226/.gems/gems/multi_json-0.0.4/lib/multi_json.rb:7:in`engine'
        from /home/BUS/djd226/.gems/gems/multi_json-0.0.4/lib/multi_json.rb:62:in `decode'
        from /home/BUS/djd226/.gems/gems/faraday-middleware-0.0.1/lib/faraday/multi_json.rb:8:in`register_on_complete'
        from /home/BUS/djd226/.gems/gems/faraday-0.4.6/lib/faraday/response.rb:45:in `call'
        from /home/BUS/djd226/.gems/gems/faraday-0.4.6/lib/faraday/response.rb:45:in`finish'
        from /home/BUS/djd226/.gems/gems/faraday-0.4.6/lib/faraday/response.rb:45:in `each'
        from /home/BUS/djd226/.gems/gems/faraday-0.4.6/lib/faraday/response.rb:45:in`finish'
        from /home/BUS/djd226/.gems/gems/faraday-0.4.6/lib/faraday/builder.rb:18:in `inner_app'
        from /home/BUS/djd226/.gems/gems/faraday-0.4.6/lib/faraday/response.rb:17:in`call'
        from /home/BUS/djd226/.gems/gems/faraday-0.4.6/lib/faraday/response.rb:17:in `call'
        from /home/BUS/djd226/.gems/gems/faraday-0.4.6/lib/faraday/adapter/net_http.rb:45:in`call'
        from /home/BUS/djd226/.gems/gems/faraday-0.4.6/lib/faraday/request.rb:84:in `run'
        from /home/BUS/djd226/.gems/gems/faraday-0.4.6/lib/faraday/request.rb:26:in`run'
        from /home/BUS/djd226/.gems/gems/faraday-0.4.6/lib/faraday/connection.rb:155:in `run_request'
        from /home/BUS/djd226/.gems/gems/faraday-0.4.6/lib/faraday/connection.rb:53:in`get'
        from /home/BUS/djd226/.gems/gems/gowalla-0.2.1/lib/gowalla/client.rb:27:in `user'

**Comment by ehutzelman** [comment]
Are you on Ruby 1.8?  I've noticed something similar to this while running tests on 1.8, need to investigate further.

**Comment by ehutzelman** [comment]
This error is the result of having no matching JSON engine installed which multi_json is looking for.  If you do a 'gem install json', then this problem should go away.

This is an interesting problem that should probably be documented better because you need at least one JSON engine installed for multi_json to work.  However, multi_json doesn't have any specific engine runtime dependencies.  Maybe we need to require an engine as part of the faraday-middleware dependencies - or make it clear that one needs to be installed before the gem will function.
